# These are supported funding model platforms

ko_fi: netwatch
# github: [wieczoj]              # uncomment when GitHub Sponsors is approved
# patreon: yourpatreon           # if you create Patreon
# liberapay: yournick            # if you create Liberapay
# custom: ['https://yourdomain.com/donate']
